module.exports = {
  seat1Row1: 'main > section div:nth-child(1) > span:nth-child(1)',
  seat2Row1: 'main > section div:nth-child(1) > span:nth-child(2)',
  seat3Row1: 'main > section div:nth-child(1) > span:nth-child(3)',
  seat4Row1: 'main > section div:nth-child(1) > span:nth-child(4)',
  seat5Row1: 'main > section div:nth-child(1) > span:nth-child(5)',
  seat6Row1: 'main > section div:nth-child(1) > span:nth-child(6)',
  seat7Row1: 'main > section div:nth-child(1) > span:nth-child(7)',
  seat8Row1: 'main > section div:nth-child(1) > span:nth-child(8)',
  seat9Row1: 'main > section div:nth-child(1) > span:nth-child(9)',
  seat10Row1: 'main > section div:nth-child(1) > span:nth-child(10)',

  seat1Row2: 'main > section div:nth-child(2) > span:nth-child(1)',
  seat2Row2: 'main > section div:nth-child(2) > span:nth-child(2)',
  seat3Row2: 'main > section div:nth-child(2) > span:nth-child(3)',
  seat4Row2: 'main > section div:nth-child(2) > span:nth-child(4)',
  seat5Row2: 'main > section div:nth-child(2) > span:nth-child(5)',
  seat6Row2: 'main > section div:nth-child(2) > span:nth-child(6)',
  seat7Row2: 'main > section div:nth-child(2) > span:nth-child(7)',
  seat8Row2: 'main > section div:nth-child(2) > span:nth-child(8)',
  seat9Row2: 'main > section div:nth-child(2) > span:nth-child(9)',
  seat10Row2: 'main > section div:nth-child(2) > span:nth-child(10)',

  seat1Row3: 'main > section div:nth-child(3) > span:nth-child(1)',
  seat2Row3: 'main > section div:nth-child(3) > span:nth-child(2)',
  seat3Row3: 'main > section div:nth-child(3) > span:nth-child(3)',
  seat4Row3: 'main > section div:nth-child(3) > span:nth-child(4)',
  seat5Row3: 'main > section div:nth-child(3) > span:nth-child(5)',
  seat6Row3: 'main > section div:nth-child(3) > span:nth-child(6)',
  seat7Row3: 'main > section div:nth-child(3) > span:nth-child(7)',
  seat8Row3: 'main > section div:nth-child(3) > span:nth-child(8)',
  seat9Row3: 'main > section div:nth-child(3) > span:nth-child(9)',
  seat10Row3: 'main > section div:nth-child(3) > span:nth-child(10)',

  seat1Row4: 'main > section div:nth-child(4) > span:nth-child(1)',
  seat2Row4: 'main > section div:nth-child(4) > span:nth-child(2)',
  seat3Row4: 'main > section div:nth-child(4) > span:nth-child(3)',
  seat4Row4: 'main > section div:nth-child(4) > span:nth-child(4)',
  seat5Row4: 'main > section div:nth-child(4) > span:nth-child(5)',
  seat6Row4: 'main > section div:nth-child(4) > span:nth-child(6)',
  seat7Row4: 'main > section div:nth-child(4) > span:nth-child(7)',
  seat8Row4: 'main > section div:nth-child(4) > span:nth-child(8)',
  seat9Row4: 'main > section div:nth-child(4) > span:nth-child(9)',
  seat10Row4: 'main > section div:nth-child(4) > span:nth-child(10)',

  seat1Row5: 'main > section div:nth-child(5) > span:nth-child(1)',
  seat2Row5: 'main > section div:nth-child(5) > span:nth-child(2)',
  seat3Row5: 'main > section div:nth-child(5) > span:nth-child(3)',
  seat4Row5: 'main > section div:nth-child(5) > span:nth-child(4)',
  seat5Row5: 'main > section div:nth-child(5) > span:nth-child(5)',
  seat6Row5: 'main > section div:nth-child(5) > span:nth-child(6)',
  seat7Row5: 'main > section div:nth-child(5) > span:nth-child(7)',
  seat8Row5: 'main > section div:nth-child(5) > span:nth-child(8)',
  seat9Row5: 'main > section div:nth-child(5) > span:nth-child(9)',
  seat10Row5: 'main > section div:nth-child(5) > span:nth-child(10)',

  vipSeatRow1:
    'section  div:nth-child(1) > span.buying-scheme__chair.buying-scheme__chair_vip',
};
